### ISSUE TITLE
Dataset help

### ISSUE THREAD

**Issue by simlebigboy** [CESNET/cesnet-datazoo#2]
Hello author, I am conducting scientific research on application identification of encrypted traffic. I found that your dataset is a new one related to QUIC and TLS. The parsed csv file is provided on GitHub, can you provide the original file in pcap format? The dataset is for scientific research purposes only. Looking forward to your recovery!

**Comment by janluxemburk** [comment]
Hello, unfortunately we don't have a pcap file for this dataset because it was created using ipfixprobe [https://github.com/CESNET/ipfixprobe](https://github.com/CESNET/ipfixprobe)  on live traffic.
