### ISSUE TITLE
Unable to download datasets due to your server failure

### ISSUE THREAD

**Issue by yurhett** [CESNET/cesnet-datazoo#3]
We noticed a strange error when running the download function:

```
KeyError: 'content-length'
```

After analyzing the download link is actually:
```
https://liberouter.org/datazoo/download?bucket=cesnet-tls22&file=CESNET-TLS22-XS.h5
```

Internal Server Error !
Your server is experiencing an outage

**Comment by hynekkar** [comment]
Thank you for the issue. There is an outage in our S3 storage. We expect to restore functionality tomorrow.

**Comment by yurhett** [comment]
Thank you for your timely response! Hopefully service will be restored soon!

**Comment by hynekkar** [comment]
The service has been finally restored. You should now be able to download datasets without any issues.

**Comment by yurhett** [comment]
It works fine! Thank you for your timely response.

**Comment by janluxemburk** [comment]
If you downloaded datasets between 21.2. and 26.2. of 2024, please remove servicemap.csv files from the dataset folders and let the library redownload these files. Wrong files were uploaded in this period.
